## Using NumPy

Once you've installed NumPy you can import it as a library:

In [10]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.


## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [11]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [12]:

import numpy as np
np.array(my_list)

array([1, 2, 3])

In [13]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [14]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [15]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [16]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones

In [17]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [18]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [19]:
np.ones(3)

array([ 1.,  1.,  1.])

In [20]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [21]:
np.full((2, 2), 7)

array([[7, 7],
       [7, 7]])

In [22]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [23]:
np.random.random((2, 2))

array([[ 0.23336704,  0.65315917],
       [ 0.11954693,  0.22839247]])

# NumPy Indexing and Selection

In this section we will discuss how to select elements or groups of elements from an array.

Let's declare an array, for better understanding of NumPy Indexing and Selection

In [24]:
a = np.array([ [1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Selecting a part of the array and assigning to another variable.

In [25]:
b = a[:2, 1:3]
b

array([[2, 3],
       [6, 7]])

Accessing elements from array is done by specifing index of the element to access the array.

In [26]:
a[0, 1]

2

In [27]:
a[1,:]

array([5, 6, 7, 8])

In [28]:
a[1:2, :]

array([[5, 6, 7, 8]])

# NumPy Operations

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [41]:
x = np.array([[1,2], [3,4]])
y = np.array([[5,6], [7,8]])

print(x)
print(y)
#print(v)

SyntaxError: invalid syntax (<ipython-input-41-0548ed4057ea>, line 3)

Addition

In [39]:
x = np.add(x,y)
print(x)

[[31 38]
 [45 52]]


Substraction

In [42]:
x - y

array([[26, 32],
       [38, 44]])

Element-wise multiplication

In [43]:
x * y

array([[155, 228],
       [315, 416]])

Element-wise division

In [44]:
y / x

array([[ 0.16129032,  0.15789474],
       [ 0.15555556,  0.15384615]])

In [45]:
1 / x

array([[ 0.03225806,  0.02631579],
       [ 0.02222222,  0.01923077]])

Raising the values of array to the power of 'n'

In [ ]:
#3 denotes the matrix is raised to the power 3
x ** 3

## Array functions

In [46]:
np.sqrt(x)

array([[ 5.56776436,  6.164414  ],
       [ 6.70820393,  7.21110255]])

In [47]:
np.exp(x)

array([[  2.90488497e+13,   3.18559318e+16],
       [  3.49342711e+19,   3.83100800e+22]])

In [48]:
np.sin(x)

array([[-0.40403765,  0.29636858],
       [ 0.85090352,  0.98662759]])

In [49]:
np.log(x)

array([[ 3.4339872 ,  3.63758616],
       [ 3.80666249,  3.95124372]])

## Transpose arrays

In [ ]:
x = np.array([[1,2], [3,4]])
x

#### The .T attribute of numpy in transposing.

In [ ]:
x.T

In [ ]:
x

In [ ]:
v = np.array([[1,2,3],[4,5,6]])
v

In [ ]:
v.T

In [ ]:
v